version: '3'
services:

  mongodb:
        image: mongo:latest
        container_name: "mongodb2"
        environment:
          - MONGO_INITDB_DATABASE=projet
          #- MONGO_INITDB_ROOT_PASSWORD=GH15935746
          #- MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        
        ports:
            - 27018:27017
  
  

  